apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: serniczek/fib-worker
          env:
            - name: REDIS_HOST
              value: redis-cluster
            - name: REDIS_PORT
              value: '6379'

